Get /api/users
imevanc/backend-nc-news-project pull request #5
Opened 2022-02-14 15:41 UTC by imevanc

I've completed the Get /api/users -> ncnews - 21

2022-02-15 12:15 UTC, daviidbartlett commented on __tests__/app.test.js
> +              votes: 100,
this test is quite brittle, you may end up adding an extra properties which will cause this to fail

2022-02-15 12:15 UTC, daviidbartlett commented on __tests__/app.test.js
> +});
what if the article doesn't exist?
- bad id?
- non existent id?

2022-02-15 12:15 UTC, daviidbartlett commented on controllers/news.controllers.js
> +  updateArticleById(article_id, inc_votes).then((article) => {
can you send back an error message please?

2022-02-15 12:15 UTC, daviidbartlett commented on models/news.models.js
> +    });
shouldn't have a catch block here

2022-02-15 12:15 UTC, daviidbartlett commented on models/news.models.js
> +      return error;
again no catch block, should be in your controllers

2022-02-15 12:21 UTC, imevanc commented on controllers/news.controllers.js
> +  updateArticleById(article_id, inc_votes).then((article) => {
Do you mean that I have to modify the line 24 to _**if (Object.keys(req.body).length === 0) return res.status(400).send("Bad Request");**_ ? Doesn't that happen automatically by calling the sendStatus() with 400?

2022-02-15 14:29 UTC, popatre requested changes

2022-02-15 14:29 UTC, popatre commented on __tests__/app.test.js
> +      .expect(400);
Are there not any messages to go with these error responses? e.g, 'invalid input'?

2022-02-15 14:29 UTC, popatre commented on __tests__/app.test.js
> +            votes: expect.any(Number),
You havent actually tested that the votes have incremented. You are expecting any Number. At the moment, even if it doesnt increment the votes, it will still pass

2022-02-15 16:07 UTC, popatre requested changes

2022-02-15 16:07 UTC, popatre commented on __tests__/app.test.js
> +      .patch("/api/articles/1")
Test for:
- misspelt key on the patch object. 
- Incorrect data passed e.g. a string instead of number inc_votes: "StringNumber"
- extra keys on the patch object - what if they try to update another value as well?

2022-02-16 09:11 UTC, rogersop approved these changes

2022-02-16 09:14 UTC, merged